# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-13 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectDatas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(default='TP 03/13/16', max_length=100),
        ),
    ]
