# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-15 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectDatas', '0002_auto_20160313_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='description',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(default='TP 03/15/16', max_length=100),
        ),
    ]
