# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collectDatas', '0003_auto_20160315_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='name',
            field=models.CharField(default='TP 03/20/16', max_length=100),
        ),
    ]
